{"schema_version":"1.6.0","id":"OESA-2022-1806","modified":"2022-08-05T11:31:27Z","published":"2022-08-05T11:31:27Z","related":["CVE-2022-32746"],"summary":"libldb security update","details":"An extensible library that implements an LDAP like API to access remote LDAP servers, or use local tdb databases.\r\n\r\nSecurity Fix(es):\r\n\r\nA flaw was found in the Samba AD LDAP server. The AD DC database audit logging module can access LDAP message values freed by a preceding database module, resulting in a use-after-free issue. This issue is only possible when modifying certain privileged attributes, such as userAccountControl.(CVE-2022-32746)","affected":[{"package":{"ecosystem":"openEuler-20.03-LTS-SP1","name":"libldb","purl":"pkg:rpm/openEuler/libldb&distro=openEuler-20.03-LTS-SP1"},"ranges":[{"type":"ECOSYSTEM","events":[{"introduced":"0","fixed":"2.0.12-3.oe1"}]}],"ecosystem_specific":{"aarch64":["libldb-debugsource-2.0.12-3.oe1.aarch64.rpm","libldb-debuginfo-2.0.12-3.oe1.aarch64.rpm","python-ldb-devel-common-2.0.12-3.oe1.aarch64.rpm","libldb-devel-2.0.12-3.oe1.aarch64.rpm","libldb-2.0.12-3.oe1.aarch64.rpm","python3-ldb-2.0.12-3.oe1.aarch64.rpm","python3-ldb-devel-2.0.12-3.oe1.aarch64.rpm"],"noarch":["libldb-help-2.0.12-3.oe1.noarch.rpm"],"src":["libldb-2.0.12-3.oe1.src.rpm"],"x86_64":["libldb-2.0.12-3.oe1.x86_64.rpm","libldb-debuginfo-2.0.12-3.oe1.x86_64.rpm","libldb-debugsource-2.0.12-3.oe1.x86_64.rpm","libldb-devel-2.0.12-3.oe1.x86_64.rpm","python-ldb-devel-common-2.0.12-3.oe1.x86_64.rpm","python3-ldb-devel-2.0.12-3.oe1.x86_64.rpm","python3-ldb-2.0.12-3.oe1.x86_64.rpm"]}},{"package":{"ecosystem":"openEuler-20.03-LTS-SP3","name":"libldb","purl":"pkg:rpm/openEuler/libldb&distro=openEuler-20.03-LTS-SP3"},"ranges":[{"type":"ECOSYSTEM","events":[{"introduced":"0","fixed":"2.0.12-3.oe1"}]}],"ecosystem_specific":{"aarch64":["python3-ldb-devel-2.0.12-3.oe1.aarch64.rpm","libldb-2.0.12-3.oe1.aarch64.rpm","python-ldb-devel-common-2.0.12-3.oe1.aarch64.rpm","libldb-debugsource-2.0.12-3.oe1.aarch64.rpm","libldb-devel-2.0.12-3.oe1.aarch64.rpm","python3-ldb-2.0.12-3.oe1.aarch64.rpm","libldb-debuginfo-2.0.12-3.oe1.aarch64.rpm"],"noarch":["libldb-help-2.0.12-3.oe1.noarch.rpm"],"src":["libldb-2.0.12-3.oe1.src.rpm"],"x86_64":["libldb-debugsource-2.0.12-3.oe1.x86_64.rpm","libldb-2.0.12-3.oe1.x86_64.rpm","python-ldb-devel-common-2.0.12-3.oe1.x86_64.rpm","python3-ldb-2.0.12-3.oe1.x86_64.rpm","libldb-devel-2.0.12-3.oe1.x86_64.rpm","libldb-debuginfo-2.0.12-3.oe1.x86_64.rpm","python3-ldb-devel-2.0.12-3.oe1.x86_64.rpm"]}},{"package":{"ecosystem":"openEuler-22.03-LTS","name":"libldb","purl":"pkg:rpm/openEuler/libldb&distro=openEuler-22.03-LTS"},"ranges":[{"type":"ECOSYSTEM","events":[{"introduced":"0","fixed":"2.4.1-2.oe2203"}]}],"ecosystem_specific":{"aarch64":["libldb-2.4.1-2.oe2203.aarch64.rpm","libldb-devel-2.4.1-2.oe2203.aarch64.rpm","python3-ldb-devel-2.4.1-2.oe2203.aarch64.rpm","libldb-debugsource-2.4.1-2.oe2203.aarch64.rpm","python3-ldb-2.4.1-2.oe2203.aarch64.rpm","libldb-debuginfo-2.4.1-2.oe2203.aarch64.rpm","python-ldb-devel-common-2.4.1-2.oe2203.aarch64.rpm"],"noarch":["libldb-help-2.4.1-2.oe2203.noarch.rpm"],"src":["libldb-2.4.1-2.oe2203.src.rpm"],"x86_64":["libldb-debugsource-2.4.1-2.oe2203.x86_64.rpm","libldb-devel-2.4.1-2.oe2203.x86_64.rpm","python3-ldb-2.4.1-2.oe2203.x86_64.rpm","python-ldb-devel-common-2.4.1-2.oe2203.x86_64.rpm","python3-ldb-devel-2.4.1-2.oe2203.x86_64.rpm","libldb-2.4.1-2.oe2203.x86_64.rpm","libldb-debuginfo-2.4.1-2.oe2203.x86_64.rpm"]}}],"references":[{"type":"ADVISORY","url":"https://www.openeuler.org/en/security/safety-bulletin/detail.html?id=openEuler-SA-2022-1806"},{"type":"ADVISORY","url":"https://nvd.nist.gov/vuln/detail/CVE-2022-32746"}],"database_specific":{"severity":"Medium"}}
